"""Add created_at and updated_at to items

Revision ID: acd4c0e8bbf8
Revises: 3fcddcf12899
Create Date: 2025-12-30 21:35:52.084601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd4c0e8bbf8'
down_revision: Union[str, None] = '3fcddcf12899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ###
